### PR TITLE
Update website URL and use Blob API to generate download link

### LINKED ISSUE #22: Customized Download not working
Could you upload the custom builder to the gh-pages branch? When clicking it, I'm sent to a dead appspot url.

### PR DESCRIPTION
**Pull request by etrepum**
This should fix #22. The decommissioned appspot application only served to compress and provide a download link for the JS that was in the form post. Current browsers can do this without a server.

### CODE REVIEW

**Comment by w0298i** [comment]
Which form? Can you link it? :+1:

**Comment by etrepum** [comment]
The form in customize.html

**Comment by w0298i** [comment]
You thinking of merging this?

**Comment by etrepum** [comment]
Yes, I was waiting to see if you had other feedback.

**Comment by w0298i** [comment]
Could you maybe ask Google for the appspot back? Didn't the closure authors take over MochiKit? That's what i saw in the google homepage's code, anyway.

**Comment by etrepum** [comment]
The only thing that URL did was echo back the posted file as something you can download. That’s no longer necessary.

Google forked some of MochiKit and incorporated it into their code, they did not take over anything.

**Pull request merged**
