### PR TITLE
Added video element for easier viewability

### PR DESCRIPTION
**Pull request by w0298i**

### CODE REVIEW

**Comment by w0298i** [comment]
By the way, sorry I had to use the org account guys, already had a fork on my main. This'll be gone when this gets merged.

**Comment by w0298i** [comment]
Oh shit, your video is so large it takes so long to load. Inserting a compressed version now.

**Comment by etrepum** [comment]
You can have multiple branches in a fork on one account. It’s best not to commit a video file to a git repo, they’re not designed well for large files. Would be better to embed from another site.

**Comment by etrepum** [comment]
archive.org supports embedding these days, you could use that directly if you didn't want to embed from YouTube. https://archive.org/help/video.php

Should be something like:

```
<iframe src="https://archive.org/embed/MochiKit_Intro-1" width="640" height="480" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>
```

**Comment by w0298i** [comment]
Should I move this issue over to my repo?

**Comment by w0298i** [comment]
Seems easy enough, ill submit another from mine, sorry bout this guys, gh ui is confusing me lol

**Comment by etrepum** [comment]
It really doesn't matter, I'm just letting you know that you can have multiple PRs from the same fork. It's probably best to delete this one though, since it has large files in the commits, and if this PR is merged those commits will end up in the repo and make it a lot bigger.

In order to have multiple PRs, instead of committing directly to the master branch of your fork, you switch to a branch with a different name first. When that branch is pushed, you'll have the option in the GitHub UI to create a PR from it. Generally I would recommend against committing directly to master on a fork of a repository.

**Comment by w0298i** [comment]
Yeah sorry just not thinking, used to being flamed for this lol

**Pull request closed without merging**
